[package]
name = "wkdmgr-query"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wkdmgr-core = { path = "../wkdmgr-core" }
tokio = { workspace = true }
axum = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
