// Thin typed wrapper around the wkdmgr-mgmt `/api/*` contract. This is
// the single place in the frontend that knows the API prefix and
// response shapes; components call these functions instead of calling
// `fetch`/the generated client directly.
//
// The request/response types (`./api-types.ts`) are generated by
// `npm run generate:api` from the OpenAPI spec that `wkdmgr-mgmt
// --print-openapi` emits -- itself derived directly from the Rust
// handler/DTO definitions via `utoipa`. Rust is the single source of
// truth for the contract; nothing here is hand-typed, so the two
// implementations can't drift silently. Re-run `npm run generate:api`
// after any backend API change.
//
// Same-origin only: the SSO proxy sets the identity header on every
// request to this vhost (API calls included), so there is no auth logic
// here and no CORS handling needed.

import createClient from 'openapi-fetch'
import type { components, paths } from './api-types'

export type MeResponse = components['schemas']['MeResponse']
export type KeyResponseItem = components['schemas']['KeyResponseItem']
type ApiErrorBody = components['schemas']['ApiErrorBody']

export class ApiError extends Error {
  status: number
  code: string

  constructor(status: number, code: string, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.code = code
  }
}

const client = createClient<paths>({ baseUrl: '/' })

function unwrapError(response: Response, error: ApiErrorBody | undefined): never {
  throw new ApiError(response.status, error?.error ?? 'unknown_error', error?.message ?? `request failed with status ${response.status}`)
}

/** GET /api/me */
export async function getMe(): Promise<MeResponse> {
  const { data, error, response } = await client.GET('/api/me')
  if (error) unwrapError(response, error)
  return data
}

/** GET /api/keys */
export async function listKeys(): Promise<KeyResponseItem[]> {
  const { data, error, response } = await client.GET('/api/keys')
  if (error) unwrapError(response, error)
  return data
}

/**
 * POST /api/keys
 * `key` is ASCII-armored or base64 OpenPGP key material.
 */
export async function uploadKey(address: string, key: string): Promise<KeyResponseItem> {
  const { data, error, response } = await client.POST('/api/keys', {
    body: { address, key },
  })
  if (error) unwrapError(response, error)
  return data
}

/** DELETE /api/keys/:id */
export async function deleteKey(id: string): Promise<void> {
  const { error, response } = await client.DELETE('/api/keys/{id}', {
    params: { path: { id: Number(id) } },
  })
  if (error) unwrapError(response, error)
}
